spring:
  application:
    name: service-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
  cloud:  #分布式中心配置
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig    #配置git仓库地址
          searchPaths: respo    #配置仓库路径
          username:  #访问git仓库的用户名
          password:  #访问git仓库的用户密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/


