spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8

logging:
  config: classpath:log/logback-dev.xml

swagger:
  enable: true    #dev环境激活swagger

mybatis:
  mapper-locations: classpath:com.pc.service.com.pc.service.mapper/*.xml

