spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
  application:
    name: service-two

logging:   #logback日志
  config: classpath:log/logback-dev.xml

swagger:
  enable: true    #dev环境激活swagger

mybatis:
  mapper-locations: classpath:com.pc.service.com.pc.service.mapper/*.xml

pagehelper:   #分页插件配置
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pparams: count=countSql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true   #开启feign

ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
