spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: 123456
    url: jdbc:mysql://1.15.145.243:3306/test?characterEncoding=utf-8

logging:
  config: classpath:log/logback-dev.xml

swagger:
  enable: false    #dev环境激活swagger

mybatis:
  mapper-locations: classpath:mapper/*.xml

httpconfig:
  no-check-url:
    - /api-gateway/gateway/v1/rlzy/login

aesconfig:
  key: AD42F6697B035B7580E4FEF93BE20BAD  #密钥

public:
  base-path: /pc/base/business