server:
  port: 7007
spring:
  application:
    name: service-active
  profiles:
    active: dev
  jmx:
    default-domain: 05
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 30s

