spring:
  application:
    name: eurka-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: 123456
    url: jdbc:mysql://1.15.145.243:3306/test?characterEncoding=utf-8
