spring:
  application:
    name: eurka-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8

