server:
  port: 7001
spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  jmx:
    default-domain: 02

zuul:
  retryable: true
  add-host-header: true
  #ignored-patterns: /**/selectOne/**   #忽略某些路径不进行路由
  routes:
    service-gateway: /pc/api-gateway/**  #网关自己也要走zuul过滤
    api-business:
      path: /pc/api-business/**
      serviceId: service-business
      strip-prefix: false
    api-attributes:
      path: /pc/api-attributes/**
      serviceId: service-attributes
      strip-prefix: false

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 6000
