spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 30s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/  #服务注册中心

logging:
  config: classpath:log/logback-dev.xml

swagger:
  enable: true    #dev环境激活swagger

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pparams: count=countSql


